runtime: python-compat
env: flex
api_version: 1
threadsafe: yes
service: default

default_expiration: "1s"

handlers:
- url: /
  static_files: frontend/index.html
  upload: frontend/index.html

- url: /api/.*
  script: backend.app

- url: /(.*)
  static_files: frontend/\1
  upload: frontend/(.*)