runtime: custom
env: flex
api_version: 1
threadsafe: yes
entrypoint: gunicorn -b :$PORT main:app
service: default

default_expiration: 1s

runtime_config:
  python_version: 2

resources:
  cpu: 0.1
  memory_gb: 0.9
  disk_size_gb: 10

manual_scaling:
  instances: 1

health_check:
  enable_health_check: false